<a href="https://colab.research.google.com/github/Suthirtha2004/ml-from-scratch/blob/main/Multiclass_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [3]:
# Make 4-class dataset for classification

classes = 4
m = 100
centers = [[-5,2],[-2,-2],[1,2],[5,-2]]
std = 1.0
X_train , y_train = make_blobs(n_samples=m,centers=centers,cluster_std=std,random_state=30)

In [4]:
# Show classes in dataset
print(f"Unique classes {np.unique(y_train)}")
# Show classes are represented
print(f"Class representation {y_train[:10]}")
#Show shapes of our dataset
print(f"Shape of X_train : {X_train.shape} , shape of y_train : {y_train.shape}")

Unique classes [0 1 2 3]
Class representation [3 3 3 0 3 3 3 3 2 0]
Shape of X_train : (100, 2) , shape of y_train : (100,)


2-layer Network model the output layer uses a linear and then a softmax activation.

In [5]:
tf.random.set_seed(1234)

model = Sequential(
    [
        Dense(2,activation='relu',name = "L1"),
        Dense(4,activation ='linear',name = "L2")
    ]
)

In [6]:
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(0.01)
)

model.fit(
    X_train,y_train,
    epochs = 200
)

Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 1.5559  
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3982 
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2737 
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1670 
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0755
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9990
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9357 
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.8833
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8404 
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.8048
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7750 
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7496 
Epoch 13/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7274 
Epoch 14/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7075 
Epoch 15/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6894 
Epoch 16/200
4/4 ━

In [8]:
pre_results = model.predict(X_train)
results = tf.nn.softmax(pre_results).numpy()

print(f"The output probabilites of top 10 , {results[:10]}")

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step
The output probabilites of top 10 , [[2.64166705e-12 1.06020900e-03 4.03453591e-08 9.98939812e-01]
 [2.46223370e-13 6.02236658e-04 5.78720183e-09 9.99397635e-01]
 [4.60813842e-13 6.99280179e-04 9.66530767e-09 9.99300718e-01]
 [9.98124540e-01 1.86754589e-03 7.81183280e-06 2.90139576e-13]
 [2.42421120e-05 4.60990705e-02 1.98831540e-02 9.33993518e-01]
 [8.44623122e-18 5.19003697e-05 1.28470541e-12 9.99948084e-01]
 [4.21146317e-16 1.31839421e-04 3.14909036e-11 9.99868155e-01]
 [1.11105715e-10 2.58321571e-03 8.60150067e-07 9.97415960e-01]
 [6.12309482e-03 1.11626247e-02 9.57061291e-01 2.56529134e-02]
 [9.95713592e-01 4.22872044e-03 5.77112951e-05 1.06882983e-11]]
