<a href="https://colab.research.google.com/github/Suthirtha2004/ml-from-scratch/blob/main/Softmax_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementing softmax and cross entropy loss in Tensorflow

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs

In [3]:
data = [[-5,2],[-2,2],[1,2],[5,2]]
X_train , y_train = make_blobs(n_samples = 2000,centers=data,cluster_std=1.0,random_state=30)

# create model

model = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15,activation='relu'),
        Dense(4,activation='softmax')
    ]
)

model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.001),
)

model.fit(
    X_train,y_train,
    epochs = 10
)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.5210
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7476
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5364
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4389
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3772
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3345
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3053
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2834
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2651
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2524


In [6]:
results = model.predict(X_train)
print(results[::])
print(len(results))
print("Largest value" , np.max(results) , "Smallest value",np.min(results))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[5.0709699e-04 1.4345959e-02 9.1578197e-01 6.9364965e-02]
 [9.6096259e-01 3.8565509e-02 8.1536264e-06 4.6374547e-04]
 [8.8262033e-01 1.1491705e-01 1.7692357e-04 2.2854935e-03]
 ...
 [7.7368808e-03 7.4223924e-01 2.4105784e-01 8.9660501e-03]
 [3.3666633e-06 2.8633018e-05 4.2703822e-03 9.9569756e-01]
 [2.6919172e-04 3.9014410e-02 9.5578980e-01 4.9266065e-03]]
2000
Largest value 0.9999936 Smallest value 1.4788738e-09


Now using more precise calculation we are going to implement logits.The logits function helps us to use the loss function un the softmaz operation in the loss calculation.

In [7]:
# Preferred Model

model2 = Sequential([
    Dense(25,activation= 'relu'),
    Dense(15,activation='relu'),
    Dense(4,activation='linear') # This is used because we will be calculating loss in the loss function
])

model2.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(0.001)
)

model2.fit(
    X_train,y_train,
    epochs = 10
)


Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8209
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5027
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3970
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3439
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3118
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2883
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2696
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2520
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2408
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2320


The output we get are not probabilities they are just the computed values before the final softmax activation layer hits

In [8]:
unprocessed_results = model2.predict(X_train)
results = tf.nn.softmax(unprocessed_results).numpy()

print(f"Two output vectors:\n {results[:2]}")
print("Largest value",np.max(results),"Smallest value",np.min(results))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Two output vectors:
 [[1.6690777e-03 2.3559170e-02 8.9048254e-01 8.4289178e-02]
 [9.8336691e-01 1.6619965e-02 1.1156547e-05 1.9884094e-06]]
Largest value 0.99995774 Smallest value 2.4155916e-10
